---
driver:
  name: vagrant

provisioner:
  name: chef_zero
#  require_chef_omnibus: 11.16.4
  environments_path: "test/integration/environments"
  client_rb:
    environment: localdev

platforms:
  - name: chef11
    driver:
      vm_hostname: default-oel65-chef-java
      box: oel65-chef-java
    provisioner:
      require_chef_omnibus: 11.16.4
  - name: chef12
    driver:
      vm_hostname: default-oel65-chef-java
      box: oel65-chef-java
    provisioner:
      require_chef_omnibus: 12.12.15





suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[omc_zookeeper_test::default]
      - recipe[omc_kafka_test::default]
